---
services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - websandbox_net
    volumes:
      - websandbox_pgdata:/var/lib/postgresql/data
        
# Network and volume are already created by tf
networks:
  websandbox_net:
    external: true

volumes:
  websandbox_pgdata:
    external: true
